/**
 * TypeRush Game Mode Text Banks
 * Different texts for different game modes
 */

// ===== SPRINT MODE TEXTS (3-4 lines, ~50-100 words) =====
const SPRINT_TEXTS = [
  "The quick brown fox jumps over the lazy dog while the sun sets behind the mountains creating golden reflections on the water below.",
  "Technology is advancing faster than ever before, changing how we work, communicate, and interact with the world around us every single day.",
  "Success comes to those who persist through challenges and never give up on their dreams no matter how difficult the journey becomes.",
  "Learning to code opens doors to unlimited possibilities and allows you to create amazing applications that can impact millions of people worldwide.",
  "The future belongs to those who can adapt quickly to change and embrace new technologies with an open and curious mind always.",
  "Great leaders inspire others through their vision, passion, and dedication to excellence in everything they do every single day consistently.",
  "Reading books expands your mind and transports you to different worlds while teaching valuable lessons about life and human nature.",
  "Exercise and physical fitness are essential components of a healthy lifestyle that contribute to both mental and physical wellbeing.",
  "Coffee is a beloved beverage enjoyed by millions of people around the world for its rich flavor and energizing effects daily.",
  "Music has the power to move our emotions and connect us to others in ways that words alone simply cannot accomplish ever."
];

// ===== MARATHON MODE TEXTS (2-3 paragraphs, ~200-400 words) =====
const MARATHON_TEXTS = [
  `The art of programming is not merely about writing code that works; it is about crafting elegant solutions that are maintainable, efficient, and beautiful. When developers approach their work with the mindset of an artist, they create software that is not only functional but also a joy to read and modify. This philosophy has shaped the greatest programmers throughout history, who understood that code is primarily written for humans to read, with execution by the computer being a secondary consideration.

The journey of becoming a skilled programmer requires dedication, persistence, and an unwavering commitment to continuous learning. In today's rapidly evolving technological landscape, staying relevant means embracing new languages, frameworks, and paradigms constantly. Yet amidst all this change, the fundamental principles of good software design remain timeless and invaluable. Clean code, proper documentation, and thoughtful architecture are the hallmarks of professional development that stands the test of time.`,

  `The world we live in is increasingly powered by technology, from the smartphones in our pockets to the artificial intelligence systems that influence our daily lives in ways we often do not realize. Understanding how this technology works has become essential for everyone, not just specialists. Programming literacy is becoming as fundamental as reading and writing were in previous generations. When you understand code, you understand the systems that shape modern society, giving you power and agency in an increasingly digital world.

The beauty of programming lies in its universal applicability and the endless possibilities it offers for solving real-world problems. Whether you are interested in healthcare, entertainment, education, or any other field, programming skills enable you to make tangible impacts. Young people entering the field today have unprecedented opportunities to create applications that improve lives on a global scale. The democratization of programming through online resources and open-source communities means that talent and dedication, not privilege, determine success.`,

  `Nature has always been a source of inspiration for human creativity and scientific discovery throughout the ages. From the graceful flight of birds to the intricate patterns of snowflakes, the natural world demonstrates principles of design and engineering that far surpass human creations. Many of our greatest technological advances have come from studying and mimicking natural processes, a field known as biomimicry. As we face environmental challenges, this approach becomes increasingly valuable, offering sustainable solutions rooted in billions of years of evolutionary refinement.

The interconnectedness of all living things reminds us that we are part of a larger system, not separate from it. This perspective shift has profound implications for how we approach problem-solving and innovation. When we recognize ourselves as participants in nature rather than dominators of it, we make better decisions that benefit both humanity and the environment. The future belongs to those who can harmonize technological advancement with environmental stewardship and create a sustainable world for generations to come.`,

  `Artificial intelligence represents one of the most transformative technologies of our time, with potential applications limited only by our imagination. From healthcare diagnostics to scientific research acceleration, AI is augmenting human capabilities in unprecedented ways. Yet this powerful technology also raises important questions about ethics, privacy, and the future of work. The developers who create AI systems have a responsibility to ensure these tools are built with consideration for their impact on society and are deployed in ways that benefit humanity as a whole.

The rise of AI is not something to fear but to understand and shape thoughtfully through education, regulation, and responsible development practices. Those who learn to work effectively with AI, whether as programmers or domain experts, will be best positioned to thrive in the future economy. The intersection of human creativity and artificial intelligence capabilities promises to solve problems that have plagued humanity for centuries. Our challenge is to ensure this power is wielded wisely and that the benefits are distributed broadly across all segments of society.`,

  `The importance of mental health and well-being has never been more relevant than in today's fast-paced, high-stress world where constant connectivity means we are always reachable and always on. Taking time to disconnect, reflect, and recharge is not a luxury but a necessity for maintaining our psychological and emotional health. Practices like meditation, exercise, and spending time in nature have been scientifically proven to reduce stress, anxiety, and depression while improving overall quality of life and cognitive function significantly.

Creating a healthy work-life balance requires conscious effort and boundary-setting in an age where the lines between professional and personal time have blurred considerably. Companies and individuals alike are beginning to recognize that productivity does not increase with longer hours but rather with well-rested, fulfilled employees who have time for family, hobbies, and self-care. The future of work will likely see a continued shift toward flexibility, remote options, and a greater emphasis on employee wellbeing as organizations compete for top talent in an increasingly competitive market.`
];

// ===== ENDLESS MODE TEXTS (20 paragraphs, ~1400+ words) =====
const ENDLESS_TEXTS = [
  `The human capacity for learning and adaptation is one of our greatest strengths as a species. Throughout history, humans have overcome seemingly insurmountable challenges by combining creativity, determination, and the willingness to learn from failure. In today's world, where change is constant and uncertainty is the only certainty, the ability to learn quickly and adapt continuously has become more valuable than ever before. Those who embrace lifelong learning position themselves not just for career success but for personal fulfillment and growth throughout their lives.

The digital revolution has fundamentally transformed every aspect of human existence, from how we work and communicate to how we entertain ourselves and connect with others across the globe. The internet, once a tool for elite researchers, has become an essential utility for billions of people worldwide. This democratization of information and connectivity has created unprecedented opportunities for collaboration, innovation, and social change. Yet it has also created new challenges around misinformation, privacy, and digital divide that must be thoughtfully addressed.

Education systems around the world are slowly beginning to recognize that traditional approaches need to evolve to prepare students for an uncertain future. Critical thinking, creativity, and emotional intelligence are becoming just as important as traditional academic knowledge. Online learning platforms have made quality education accessible to people regardless of geographic location or economic status. This transformation in education is empowering individuals to take control of their learning journey and acquire skills that are relevant to their personal and professional goals.

The workplace has undergone radical transformation in the past few years, accelerated by the global pandemic that forced rapid adoption of remote work and digital collaboration tools. Many companies and employees have discovered that flexible work arrangements can increase productivity, improve work-life balance, and expand the talent pool beyond geographic limitations. This shift is challenging traditional notions of office culture and management styles, requiring leaders to focus on outcomes rather than visibility and presence. The future of work is likely to be hybrid, flexible, and increasingly distributed across global teams.

Entrepreneurship and innovation have become driving forces in modern economies, creating new industries and disrupting established ones at an accelerating pace. The barrier to entry for starting a business has never been lower thanks to cloud computing, open-source software, and online platforms for reaching customers. Young entrepreneurs armed with good ideas and determination can now launch ventures that scale to global markets in a matter of months. This democratization of entrepreneurship is fostering creativity and economic opportunity while also increasing competition and market saturation.

Sustainability and environmental responsibility are no longer optional considerations but essential business practices for companies that want to remain relevant in the twenty-first century. Climate change, resource depletion, and pollution are existential challenges that require immediate action from governments, businesses, and individuals alike. The good news is that many sustainable practices are also economically beneficial, creating opportunities for profit and positive environmental impact simultaneously. Green technology and sustainable business models are attracting investment and talented individuals who want their work to contribute to a better future.

The rise of social media and digital platforms has transformed how we communicate, share information, and build communities, for better and worse. While these platforms enable unprecedented connection and the amplification of important voices and causes, they also facilitate the spread of misinformation and create echo chambers that reinforce existing beliefs. Understanding how to critically evaluate information and engage thoughtfully in digital spaces is becoming an essential life skill. The responsibility for creating healthier digital environments falls on platform designers, regulators, and users working together.

Mental health awareness has finally begun to receive the attention it deserves, with more people acknowledging the importance of psychological wellbeing alongside physical health. Stigma around seeking therapy and discussing mental health challenges is decreasing, particularly among younger generations who are more open about their struggles. The pandemic accelerated this conversation while also exacerbating mental health challenges for many people worldwide. Creating supportive environments both online and offline is crucial for helping people maintain psychological resilience and wellbeing.

Technology companies have become some of the most powerful and influential institutions in modern society, wielding influence that rivals governments in some respects. The concentration of power in the hands of a few mega-corporations raises important questions about competition, privacy, and the appropriate role of corporations in democratic societies. Regulation of technology companies is an ongoing debate with significant implications for innovation, consumer protection, and societal wellbeing. Finding the right balance between encouraging innovation and preventing harm is one of the central challenges of our time.

Diversity and inclusion are not just moral imperatives but also business necessities that drive innovation, improve decision-making, and expand market reach. Companies that embrace diverse teams and inclusive cultures report better financial performance and are better positioned to understand and serve diverse customer bases. Creating truly inclusive environments requires more than tokenism or surface-level diversity initiatives; it requires genuine commitment to equity and dismantling systemic barriers. The journey toward inclusive organizations is ongoing and requires continuous effort and accountability.

Career development in the modern era looks very different from previous generations, with fewer lifetime companies and more frequent job changes, skills development, and pivots. Building a resilient career now involves developing a diverse set of skills, maintaining professional networks, and being willing to reinvent oneself as industries evolve. Personal branding through social media and online portfolios has become increasingly important for career advancement and attracting opportunities. The traditional linear career path has been replaced by more organic, nonlinear trajectories shaped by personal interests and market opportunities.

The globalization of supply chains and labor markets has created unprecedented economic opportunities while also creating new vulnerabilities and challenges. Companies can now source talent from anywhere in the world, fostering diverse teams but also creating competition for skilled workers. Understanding global economics, cross-cultural communication, and international relations is becoming increasingly important for anyone involved in business. The interconnectedness of global markets means that disruptions anywhere can have cascading effects across the entire world.

Personal development and growth are increasingly viewed as ongoing pursuits rather than destinations to be reached and completed. The concept of personal development encompasses not just career advancement but also emotional intelligence, physical health, creativity, and spiritual growth. Investing in yourself through learning, experiences, and relationships yields returns throughout your entire life. The tools and resources available for personal development today are extraordinary, from online courses to mentorship networks to self-help literature.

Technology's impact on healthcare has been revolutionary, enabling earlier diagnosis, more effective treatments, and better management of chronic diseases. Telemedicine has made healthcare more accessible to people in remote areas and those with mobility challenges. Artificial intelligence is being deployed to analyze medical imaging and identify patterns that might escape human doctors. Yet healthcare systems continue to face challenges around access, affordability, and equitable distribution of resources. The future of healthcare lies in combining technological innovation with holistic approaches that address social determinants of health.

The creative industries have experienced a renaissance enabled by digital tools and platforms that democratize creation and distribution of content. Tools that once required expensive equipment and professional training are now accessible to anyone with a computer and internet connection. This has unleashed enormous creative potential but also created challenges around copyright, attribution, and fair compensation for creators. The future of creative work involves finding sustainable models that fairly reward creators while enabling access and collaboration.

Community building has become increasingly important in an era of geographic dispersion and digital connection. Whether online or offline, communities provide support, belonging, and opportunities for collaboration and mutual aid. Social isolation and loneliness are recognized as serious health challenges that can be mitigated through strong communities and social connections. Technology enables community building at unprecedented scale and across geographic boundaries. The most resilient communities combine digital connection with in-person interaction and genuine relationship building.

Civic engagement and democratic participation have been transformed by digital tools that enable broader participation and organization. Social movements can now mobilize millions of people around causes they care about without traditional hierarchical structures or gatekeepers. This democratization of activism has enabled important social change but has also created challenges around coordination, sustainability, and preventing co-optation. The future of civic engagement will likely involve continued experimentation with digital tools for organizing and decision-making.

The future of transportation is being shaped by developments in electric vehicles, autonomous driving, and shared mobility solutions that promise to reduce emissions and improve safety. The transition away from fossil fuels for transportation is underway and accelerating as technology improves and costs decrease. Urban planning and city design are being reimagined around these new transportation paradigms, potentially reducing pollution, congestion, and the need for large parking areas. This transformation will have profound effects on how we live and interact with our physical spaces.

Artificial general intelligence and advanced AI systems represent both tremendous promise and significant challenges for the future of humanity. While current AI systems are narrow and task-specific, the long-term vision of artificial general intelligence raises profound questions about the nature of intelligence, consciousness, and the relationship between humans and machines. Ensuring that advanced AI systems are aligned with human values and benefit humanity broadly is one of the central challenges facing researchers and policymakers. The next few decades will likely be crucial in determining whether AI becomes a tool that amplifies human flourishing or a threat to human autonomy.

The meaning of success and fulfillment continues to evolve as people increasingly seek purpose and meaning alongside financial security and status. Many people, particularly younger generations, prioritize work that aligns with their values and makes a positive impact over maximum income and prestige. This shift in priorities is changing how organizations operate and what they offer employees beyond compensation. Building a life of meaning and fulfillment requires aligning your work, relationships, and daily practices with your core values and long-term vision for your life.`
];

module.exports = {
  SPRINT_TEXTS,
  MARATHON_TEXTS,
  ENDLESS_TEXTS
};