const TEXT_BANK = [
  "In a serious typing competition, focus starts before the race begins. Sit with your back straight, keep your shoulders relaxed, and place your fingers on the home row so every movement stays efficient. As the countdown ends, do not chase speed in the first line because panic creates mistakes that cost more time than they save. Read two or three words ahead, keep a steady rhythm, and trust your muscle memory to carry you through difficult letter combinations. When you make an error, correct it immediately without emotional reaction and continue with calm precision. Winners are not always the fastest sprinters; they are the most consistent typists from first word to last.",
  "Strong typing performance is built through daily repetition, not random bursts of motivation. Practice punctuation, numbers, and capital letters because real race text is never limited to simple lowercase words. Track your accuracy first and your speed second, since clean output produces better final results than wild typing with frequent corrections. Learn common word patterns and letter transitions so your fingers move naturally without searching for keys. If your hands become tense, pause briefly, shake out your wrists, and reset your posture before continuing. Consistency over many sessions creates durable progress that appears in every race. The goal is to reach a flow state where your eyes scan ahead while your fingers execute with minimal hesitation.",
  "A competitive race often feels intense when other players surge forward on the progress bar, but discipline matters more than fear. Keep your breathing steady and avoid staring at your opponents for too long because distraction breaks your cadence. Use short visual chunks of text and type each chunk cleanly before moving to the next phrase. If a difficult sentence appears, reduce speed slightly, lock in accuracy, and recover momentum with confidence. Most races are decided by error control in the final section, not reckless speed at the beginning. Treat each keystroke as a small decision that contributes to your final score. Precision under pressure is the difference between finishing well and falling apart near the end.",
  "Typing skill transfers to school, work, coding, communication, and almost every digital task you perform each day. Faster and cleaner input lets you think directly in words without fighting the keyboard, which improves both productivity and clarity. The best training routine includes timed tests, free writing, and focused drills for weak letters or symbols that slow you down. Review your mistakes after each session and notice whether errors happen from rushing, poor finger placement, or unfamiliar vocabulary. Then build a short drill that attacks that exact weakness until it becomes comfortable. Progress may look slow week to week, but small gains compound strongly over months. Reliable technique beats temporary hype and creates lasting typing confidence.",
  "When preparing for a multiplayer match, set up your environment so nothing steals attention during the race. Use a stable keyboard, keep your chair height comfortable, and position your screen at eye level to reduce neck strain over longer sessions. Close unnecessary tabs, silence notifications, and give yourself a clear two minute warmup with easy sentences before the main event starts. During the race, keep your eyes on the upcoming words instead of the keys, and let touch memory guide your fingers naturally. If you notice repeated mistakes on specific characters, slow down slightly for one line, reset control, and then accelerate again. Strategic pacing converts raw potential into an actual winning performance.",
  "Advanced typists understand that rhythm is a technical skill, not just a feeling. They maintain consistent key travel, avoid slamming keys, and use balanced hand movement to reduce fatigue during long passages. A smooth tempo helps the brain predict word structure and reduces hesitation when unusual terms appear in the text. If your rhythm breaks after an error, recover by typing the next three words deliberately and then return to your normal pace. This simple reset method prevents one mistake from becoming a chain of additional errors. Over time you will notice cleaner accuracy curves, better endurance, and higher average words per minute across full races. Mastery looks calm from the outside because control replaces panic at every stage.",
  "Mental focus is often the hidden factor behind competitive typing results. Before each attempt, decide on one clear objective such as eighty eight percent accuracy minimum or a target speed that you can sustain through the final sentence. During the run, avoid negative self talk because internal noise steals working memory that should be used for reading ahead and motor execution. If your score dips, treat it as data and adjust technique on the next attempt instead of reacting emotionally. Build short recovery habits like a deep breath and relaxed shoulders between rounds to protect consistency. Confidence comes from evidence, and evidence comes from structured practice. Train smart, review honestly, and your race outcomes will improve steadily.",
  "Great racers combine technical precision with tactical awareness from start to finish. At the opening line they establish control, in the middle section they maintain tempo, and near the end they manage risk based on current accuracy. If you are leading, protect the advantage with clean typing; if you are behind, increase speed carefully without destroying correctness. Learn to recognize when a word is visually tricky and give it a fraction of extra attention before pressing the final key. Small tactical choices like these create measurable differences over long texts. Typing competitions reward complete performance, not isolated moments of speed. Stay composed, stay accurate, and finish every race with the same focus you had at the beginning."
];

module.exports = { TEXT_BANK };
